version: '3.8'
services:
  db:
    container_name: dev_db
    image: postgres:15.1-alpine
    expose:
      - 32700
    ports:
      - "32700:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ylab_menu
      PGDATA: "/g/python_project/ylab_fastapi/postgresql/data"
      POSTGRES_INITDB_ARGS: "-A md5"
  redis:
    container_name: dev_redis
    image: redis:latest
    expose:
      - 6379
    ports:
      - "9000:6379"
  rabbitmq:
    container_name: dev_rabbit
    image: rabbitmq:3.10.7-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
      - RABBITMQ_DEFAULT_VHOST=rabbit_dev
    ports:
      - "15672:15672"
      - "5672:5672"
