version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    container_name: prod_db
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ylab_menu
      PGDATA: "/g/python_project/ylab_fastapi/postgresql/prod_data"
      POSTGRES_INITDB_ARGS: "-A md5"
    networks:
      - ylab_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ylab_menu"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name:
      fastapi
    entrypoint: "uvicorn main:app --host 0.0.0.0"
    ports:
      - "8000:8000"
    env_file:
      - prod.env
    depends_on:
     db:
       condition: service_healthy
     redis:
       condition: service_healthy
    networks:
      - ylab_network
  redis:
    container_name: dev_redis
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ylab_network
networks:
  ylab_network:
    driver: bridge
